const path = require("path");

module.exports = {
  apps: [
    {
      name: "sharqiya-api",
      script: "dist/main.js",
      cwd: path.join(__dirname, "sharqiya_backend"),
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3072,
      },
      max_memory_restart: "512M",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      merge_logs: true,
      time: true,
      autorestart: true,
      watch: false,
    },
    {
      name: "sharqiya-website",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3070 -H 0.0.0.0",
      cwd: path.join(__dirname, "sharqiya_website"),
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3070,
        HOSTNAME: "0.0.0.0",
        API_URL: "http://127.0.0.1:3072",
      },
      max_memory_restart: "768M",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      merge_logs: true,
      time: true,
      autorestart: true,
      watch: false,
    },
    {
      name: "sharqiya-dashboard",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3071 -H 0.0.0.0",
      cwd: path.join(__dirname, "sharqiya_dashboard"),
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3071,
        HOSTNAME: "0.0.0.0",
      },
      max_memory_restart: "768M",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      merge_logs: true,
      time: true,
      autorestart: true,
      watch: false,
    },
  ],
};
